# Generated by Django 2.0.1 on 2018-02-22 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bulkproduct',
            name='pid',
            field=models.TextField(default=1),
        ),
    ]
