# Generated by Django 2.0.1 on 2018-02-22 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_bulkproduct_pid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bulkproduct',
            name='quantity',
            field=models.IntegerField(default=-1),
        ),
        migrations.AlterField(
            model_name='bulkproduct',
            name='reorder_quantity',
            field=models.IntegerField(default=-1),
        ),
        migrations.AlterField(
            model_name='bulkproduct',
            name='reorder_trigger',
            field=models.IntegerField(default=-1),
        ),
    ]
