# Generated by Django 2.0.2 on 2018-03-07 10:42

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_auto_20180306_0836'),
    ]

    operations = [
        migrations.AddField(
            model_name='productimage',
            name='create_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='productimage',
            name='last_modified',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
